debug_mode = True
do_time_selected =True
PAPER_BOT_ID="4228101", #虚拟账户
REAL_BOT_ID ="4740610", # 真实账户 机器人
CUR_RUNING_MULTI_BOT=""

ON_LINE_DEAL_BOT_ID1="5455831"
ON_LINE_DEAL_BOT_ID2="5394732"
ON_LINE_DEAL_BOT_ID3="5525939"
ON_LINE_DEAL_BOT_ID4="5525950"

CHROME_PATH="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

_3COMAS_NEW_ONLINE_DEAL_URL1="https://3commas.io/zh/bots/"+ON_LINE_DEAL_BOT_ID1
_3COMAS_NEW_ONLINE_DEAL_URL2="https://3commas.io/zh/bots/"+ON_LINE_DEAL_BOT_ID2
_3COMAS_NEW_ONLINE_DEAL_URL3="https://3commas.io/zh/bots/"+ON_LINE_DEAL_BOT_ID3
_3COMAS_NEW_ONLINE_DEAL_URL4="https://3commas.io/zh/bots/"+ON_LINE_DEAL_BOT_ID4

CMD1=CHROME_PATH +" "+ _3COMAS_NEW_ONLINE_DEAL_URL1
CMD2=CHROME_PATH +" "+ _3COMAS_NEW_ONLINE_DEAL_URL2
CMD3=CHROME_PATH +" "+ _3COMAS_NEW_ONLINE_DEAL_URL3
CMD4=CHROME_PATH +" "+ _3COMAS_NEW_ONLINE_DEAL_URL4

OPEN_ONLINE_DEAL_URL_CMDS = [CMD1,CMD2,CMD3,CMD4]
NEW_ON_LINE_BOT_IDS = [ON_LINE_DEAL_BOT_ID1,ON_LINE_DEAL_BOT_ID2,ON_LINE_DEAL_BOT_ID3,ON_LINE_DEAL_BOT_ID4]