debug_mode = True
do_time_selected =True
ON_LINE_DEAL_BOT_ID1="5455831"
ON_LINE_DEAL_BOT_ID2="5394732"

CHROME_PATH="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

_3COMAS_NEW_ONLINE_DEAL_URL1="https://3commas.io/zh/bots/"+ON_LINE_DEAL_BOT_ID1
_3COMAS_NEW_ONLINE_DEAL_URL2="https://3commas.io/zh/bots/"+ON_LINE_DEAL_BOT_ID2

CMD1=CHROME_PATH +" "+ _3COMAS_NEW_ONLINE_DEAL_URL1
CMD2=CHROME_PATH +" "+ _3COMAS_NEW_ONLINE_DEAL_URL2

OPEN_ONLINE_DEAL_URL_CMDS = [CMD1,CMD2]
NEW_ON_LINE_BOT_IDS = [ON_LINE_DEAL_BOT_ID1,ON_LINE_DEAL_BOT_ID2] 